APFixedPointTest.cpp: fix C++20 compilation error
Starting from C++20, the equality comparison should be reversible, i.e.
the expression `A == B` and `B == A` should select the same overload for
`operator==()`. If this does not happen, the language treats the call to
`operator==()` as ambiguous.

The ASSERT_EQ performs an equality comparison under the hood, using
`operator==()`. In the following expression, the LHS has type int64_t,
while the RHS had type uint64_t before this commit.

  ASSERT_EQ(APFixedPoint::getMax(Sema).getIntPart(), Expected);

Because of the operator overloads of `APSInt`, this caused the call to
`operator==()` hidden inside ASSERT_EQ to be ambiguous between:

1) /orchestra/sources/llvm/llvm/include/llvm/ADT/APInt.h:2035:13:
inline bool operator==(uint64_t V1, const APInt &V2) { return V2 == V1; }
            ^
2) /orchestra/sources/llvm/llvm/include/llvm/ADT/APSInt.h:339:13:
inline bool operator==(int64_t V1, const APSInt &V2) { return V2 == V1; }
            ^

The ambiguity is resolved changing the type of `Expected` to `int64_t`.